/* eslint-disable prettier/prettier */
export const CREATE_VIEW_CONFIG = 'CREATE_VIEW_CONFIG';
export const UPDATE_VIEW_CONFIG = 'UPDATE_VIEW_CONFIG';
export const USER_DATA_FETCH_REQUESTED = 'USER_DATA_FETCH_REQUESTED';
export const USER_DATA_FETCH_SUCCEEDED = 'USER_DATA_FETCH_SUCCEEDED';
export const USER_DATA_FETCH_FAILED = 'USER_DATA_FETCH_FAILED';
