/* eslint-disable prettier/prettier */
export const USER_DATA_FETCH_REQUESTED = 'USER_DATA_FETCH_REQUESTED';
export const USER_DATA_FETCH_SUCCEEDED = 'USER_DATA_FETCH_SUCCEEDED';
export const USER_DATA_FETCH_FAILED = 'USER_DATA_FETCH_FAILED';
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
export const UPDATE_USER_DATA_SUCCEEDED = 'UPDATE_USER_DATA';
export const UPDATE_USER_DATA_FAILED = 'UPDATE_USER_DATA';
